<Project>

  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <NoWarn>$(NoWarn);CA1707;CA1848;CA1805;CA1305;CA1720;CA2201;CA1822;CA2016;CA1869;CA1711;NU1510;IDE0062;IDE0044;CA1311;CA1304;CA1862;CA1850;CA1826;CA1725;CA1050;CA1001;CA1000;CA1873</NoWarn>
  </PropertyGroup>

</Project>
