<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ccxt" Version="4.5.34" />
    <PackageReference Include="CliWrap" Version="3.10.0" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ArbiScannerWeb.Domain/ArbiScannerWeb.Domain.csproj" />
  </ItemGroup>

</Project>
