// <auto-generated />
using System;
using ArbiScannerWeb.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArbiScannerWeb.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.AccountModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserSettingsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingsId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.ExchangeLinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Funding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Futures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExchangeLinks");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.ExchangeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.TelegramLinkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TelegramLinkRequests");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.UserExchangeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserSettingsModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("UserSettingsModelId");

                    b.ToTable("UserExchanges");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.UserSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FundingSpread")
                        .HasColumnType("boolean");

                    b.Property<bool>("FuturesSpread")
                        .HasColumnType("boolean");

                    b.Property<bool>("HaveAccess")
                        .HasColumnType("boolean");

                    b.Property<int>("PositionSize")
                        .HasColumnType("integer");

                    b.Property<bool>("SpotSpread")
                        .HasColumnType("boolean");

                    b.Property<double>("SpreadSize")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_UserSettings_AccountId");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_UserSettings_ChatId");

                    b.HasIndex(new[] { "SpreadSize" }, "IX_UserSettings_Active_Funding_SpreadSize")
                        .HasFilter("\"Active\" = true AND \"FundingSpread\" = true");

                    b.HasIndex(new[] { "SpreadSize" }, "IX_UserSettings_Active_Futures_SpreadSize")
                        .HasFilter("\"Active\" = true AND \"FuturesSpread\" = true");

                    b.HasIndex(new[] { "SpreadSize" }, "IX_UserSettings_Active_Spot_SpreadSize")
                        .HasFilter("\"Active\" = true AND \"SpotSpread\" = true");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.AccountModel", b =>
                {
                    b.HasOne("ArbiScannerWeb.Domain.Models.UserSettingsModel", "UserSettings")
                        .WithOne()
                        .HasForeignKey("ArbiScannerWeb.Domain.Models.AccountModel", "UserSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.UserExchangeModel", b =>
                {
                    b.HasOne("ArbiScannerWeb.Domain.Models.ExchangeModel", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArbiScannerWeb.Domain.Models.UserSettingsModel", null)
                        .WithMany("Exchanges")
                        .HasForeignKey("UserSettingsModelId");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("ArbiScannerWeb.Domain.Models.UserSettingsModel", b =>
                {
                    b.Navigation("Exchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
